server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: spring-cloud-eureka-client-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
             allowedOrigins: "*"
             allowedMethods: "*"
             allowedHeaders: "*"
      routes:
        - id: category
          uri: lb://SPRING-CLOUD-EUREKA-CLIENT-CATEGORY
          predicates:
            - Path=/category/**
        - id: author
          uri: lb://SPRING-CLOUD-EUREKA-CLIENT-AUTHOR
          predicates:
            - Path=/author/**
        - id: game
          uri: lb://SPRING-CLOUD-EUREKA-CLIENT-GAME
          predicates:
            - Path=/game/**
        - id: customer
          uri: lb://SPRING-CLOUD-EUREKA-CLIENT-CUSTOMER
          predicates:
            - Path=/customer/**
        - id: booking
          uri: lb://SPRING-CLOUD-EUREKA-CLIENT-BOOKING
          predicates:
            - Path=/booking/**
        